language: java
services:
  - xvfb
sudo: false
jdk:
- openjdk11
branches:
  only:
  - java11
install:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script: mvn clean install -U -B 

deploy:
  on:
    branch: java11
  provider: script
  script: "mvn deploy"
  skip_cleanup: true
